import type { Rule } from 'eslint'
import { analyzeEvaluatorDataFlow, planEvaluatorFrames } from '@engine262/babel-compiler'
import { getEngine262Settings, getParserServices } from './utils.mjs'
import { checkGCRelatedInternalFunctionCalls, sharedMessages } from './gc-captures-shared.mjs'

const messages = {
    ...sharedMessages,
    handwrittenFrame:
        'captureEvaluatorFrame() is generated by @engine262/babel-compiler and must not be written by hand.',
    cannotTransform: '{{reason}}',
}

export default {
    meta: {
        fixable: 'code',
        messages,
    },
    create(context) {
        const settings = getEngine262Settings(context)
        if (!settings.compiler) return {}
        const services = getParserServices(context, 'gc-captures')
        const checker = services.program.getTypeChecker()
        return {
            Program() {
                const flows = analyzeEvaluatorDataFlow(context.physicalFilename, {
                    program: services.program!,
                    valueDefinitionPath: settings.valueDefinitionPath,
                })
                const result = planEvaluatorFrames(flows)
                for (const diagnostic of result.diagnostics) {
                    context.report({
                        loc: {
                            start: context.sourceCode.getLocFromIndex(diagnostic.yield.start),
                            end: context.sourceCode.getLocFromIndex(diagnostic.yield.end),
                        },
                        messageId: 'cannotTransform',
                        data: { reason: diagnostic.message },
                    })
                }
            },
            'CallExpression, NewExpression'(node: Rule.Node) {
                checkGCRelatedInternalFunctionCalls(node, checker, services, context, (_call, reportNode) => {
                    context.report({ node: reportNode, messageId: 'handwrittenFrame' })
                })
            },
        } satisfies Rule.RuleListener
    },
} satisfies Rule.RuleModule
