name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Set everything up
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@master
        with:
          node-version: 18
      - run: git submodule update --init --recursive

      # build and lint
      - run: npm install
      - run: npm run build
      - run: npm run lint

      # upload build artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: engine262-dist
          path: |
            dist/engine262.js
            dist/engine262.js.map
            dist/engine262.mjs
            dist/engine262.mjs.map

      # run tests/coverage
      - run: npm run coverage
        env:
          CONTINUOUS_INTEGRATION: 1

      # Upload coverage data
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{github.token}}
