name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Set everything up
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      # build and lint
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run api:check
      - run: pnpm run lint

      # upload build artifacts
      - uses: actions/upload-artifact@v7
        with:
          name: engine262-lib
          path: |
            lib/engine262.js
            lib/engine262.js.map
            lib/engine262.mjs
            lib/engine262.mjs.map

      # run tests/coverage
      - run: pnpm run coverage
        env:
          CONTINUOUS_INTEGRATION: 1
          NUM_WORKERS: 1

      # Upload coverage data
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{github.token}}
